var DATA = [
      { id:0, label:"create-idea", link:"mule/brightidea.html#create-idea", type:"method" },
      { id:1, label:"get-affiliate-list", link:"mule/brightidea.html#get-affiliate-list", type:"method" },
      { id:2, label:"get-api-call-list", link:"mule/brightidea.html#get-api-call-list", type:"method" },
      { id:3, label:"get-api-data", link:"mule/brightidea.html#get-api-data", type:"method" },
      { id:4, label:"get-idea-list-for-affiliate", link:"mule/brightidea.html#get-idea-list-for-affiliate", type:"method" },
      { id:5, label:"get-idea-list-for-member", link:"mule/brightidea.html#get-idea-list-for-member", type:"method" },
      { id:6, label:"get-permission-list", link:"mule/brightidea.html#get-permission-list", type:"method" },
      { id:7, label:"org.mule.modules.brightidea", link:"java/org/mule/modules/brightidea/package-summary.html", type:"package" },
      { id:8, label:"org.mule.modules.brightidea.BrightIdeaConnector", link:"java/org/mule/modules/brightidea/BrightIdeaConnector.html", type:"class" },
      { id:9, label:"org.mule.modules.brightidea.DateAdapter", link:"java/org/mule/modules/brightidea/DateAdapter.html", type:"class" },
      { id:10, label:"org.mule.modules.brightidea.Idea", link:"java/org/mule/modules/brightidea/Idea.html", type:"class" },
      { id:11, label:"org.mule.modules.brightidea.Ideas", link:"java/org/mule/modules/brightidea/Ideas.html", type:"class" },
      { id:12, label:"org.mule.modules.brightidea.config", link:"java/org/mule/modules/brightidea/config/package-summary.html", type:"package" },
      { id:13, label:"org.mule.modules.brightidea.config.BrightIdeaConnectorCapabilitiesAdapter", link:"java/org/mule/modules/brightidea/config/BrightIdeaConnectorCapabilitiesAdapter.html", type:"class" },
      { id:14, label:"org.mule.modules.brightidea.config.BrightIdeaConnectorLifecycleAdapter", link:"java/org/mule/modules/brightidea/config/BrightIdeaConnectorLifecycleAdapter.html", type:"class" },
      { id:15, label:"org.mule.modules.brightidea.config.CreateIdeaMessageProcessor", link:"java/org/mule/modules/brightidea/config/CreateIdeaMessageProcessor.html", type:"class" },
      { id:16, label:"org.mule.modules.brightidea.config.GetAffiliateListMessageProcessor", link:"java/org/mule/modules/brightidea/config/GetAffiliateListMessageProcessor.html", type:"class" },
      { id:17, label:"org.mule.modules.brightidea.config.GetApiCallListMessageProcessor", link:"java/org/mule/modules/brightidea/config/GetApiCallListMessageProcessor.html", type:"class" },
      { id:18, label:"org.mule.modules.brightidea.config.GetApiDataMessageProcessor", link:"java/org/mule/modules/brightidea/config/GetApiDataMessageProcessor.html", type:"class" },
      { id:19, label:"org.mule.modules.brightidea.config.GetIdeaListForAffiliateMessageProcessor", link:"java/org/mule/modules/brightidea/config/GetIdeaListForAffiliateMessageProcessor.html", type:"class" },
      { id:20, label:"org.mule.modules.brightidea.config.GetIdeaListForMemberMessageProcessor", link:"java/org/mule/modules/brightidea/config/GetIdeaListForMemberMessageProcessor.html", type:"class" },
      { id:21, label:"org.mule.modules.brightidea.config.GetPermissionListMessageProcessor", link:"java/org/mule/modules/brightidea/config/GetPermissionListMessageProcessor.html", type:"class" },
      { id:22, label:"org.mule.modules.brightidea.config.spring", link:"java/org/mule/modules/brightidea/config/spring/package-summary.html", type:"package" },
      { id:23, label:"org.mule.modules.brightidea.config.spring.BrightIdeaConnectorConfigDefinitionParser", link:"java/org/mule/modules/brightidea/config/spring/BrightIdeaConnectorConfigDefinitionParser.html", type:"class" },
      { id:24, label:"org.mule.modules.brightidea.config.spring.BrightIdeaConnectorNamespaceHandler", link:"java/org/mule/modules/brightidea/config/spring/BrightIdeaConnectorNamespaceHandler.html", type:"class" },
      { id:25, label:"org.mule.modules.brightidea.config.spring.CreateIdeaDefinitionParser", link:"java/org/mule/modules/brightidea/config/spring/CreateIdeaDefinitionParser.html", type:"class" },
      { id:26, label:"org.mule.modules.brightidea.config.spring.GetAffiliateListDefinitionParser", link:"java/org/mule/modules/brightidea/config/spring/GetAffiliateListDefinitionParser.html", type:"class" },
      { id:27, label:"org.mule.modules.brightidea.config.spring.GetApiCallListDefinitionParser", link:"java/org/mule/modules/brightidea/config/spring/GetApiCallListDefinitionParser.html", type:"class" },
      { id:28, label:"org.mule.modules.brightidea.config.spring.GetApiDataDefinitionParser", link:"java/org/mule/modules/brightidea/config/spring/GetApiDataDefinitionParser.html", type:"class" },
      { id:29, label:"org.mule.modules.brightidea.config.spring.GetIdeaListForAffiliateDefinitionParser", link:"java/org/mule/modules/brightidea/config/spring/GetIdeaListForAffiliateDefinitionParser.html", type:"class" },
      { id:30, label:"org.mule.modules.brightidea.config.spring.GetIdeaListForMemberDefinitionParser", link:"java/org/mule/modules/brightidea/config/spring/GetIdeaListForMemberDefinitionParser.html", type:"class" },
      { id:31, label:"org.mule.modules.brightidea.config.spring.GetPermissionListDefinitionParser", link:"java/org/mule/modules/brightidea/config/spring/GetPermissionListDefinitionParser.html", type:"class" }

    ];
